### ISSUE TITLE
markdown-link-check as a pre-commit hook?

### ISSUE THREAD

**Issue by janosh** [tcort/markdown-link-check#169]
How about making `markdown-link-check` available as a pre-commit hook? This would mean adding a `.pre-commit-hooks.yaml` file to the repo's root dir:

```yaml
- id: markdown-link-check
  name: Markdown Link Check
  description: Extracts links from markdown texts and checks they're all alive (i.e. return status 200 OK).
  entry: markdown-link-check
  language: node
  types: [markdown]
  stages: [commit, push, manual]
```

See <https://pre-commit.com#new-hooks> for details.
