### ISSUE TITLE
Document running in GitLab CI/CD Pipeline

### ISSUE THREAD

**Issue by oxr463** [tcort/markdown-link-check#231]
The README.md file only mentions GitHub Actions.

**Comment by dklimpel** [comment]
here an example:

```yaml
linkchecker:
  stage: test
  image:
    name: ghcr.io/tcort/markdown-link-check:3.11.2
    entrypoint: ["/bin/sh", "-c"]
  needs: []
  variables:
    MARKDOWN_LINK_CHECK_CONFIG_FILE: markdown-link-check-config.json
  script:
    - find . -name \*.md -print0 | xargs -0 -n1 markdown-link-check -c ${MARKDOWN_LINK_CHECK_CONFIG_FILE}
  rules:
    - changes:
      - "**/*.md"
      - ${MARKDOWN_LINK_CHECK_CONFIG_FILE}
```
