### ISSUE TITLE
Update to commander 12.1.0 brakes package

### ISSUE THREAD

**Issue by ldynia** [tcort/markdown-link-check#323]
Hey Thomas,

It looks like an update to `commander v12.1.0` breaks the tool.

```yaml
jobs:
  pre-commit-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
...
```
```
Markdown Link Check......................................................Failed
- hook id: markdown-link-check
- duration: 0.41s
- exit code: 1
/home/runner/.cache/pre-commit/repo0jplamdq/node_env-system/lib/node_modules/markdown-link-check/markdown-link-check:37
.version(pkg.version)
^
TypeError: program.version is not a function
at getInputs (/home/runner/.cache/pre-commit/repo0jplamdq/node_env-system/lib/node_modules/markdown-link-check/markdown-link-check:37:10)
at main (/home/runner/.cache/pre-commit/repo0jplamdq/node_env-system/lib/node_modules/markdown-link-check/markdown-link-check:265:20)
Node.js v18.20.2
/home/runner/.cache/pre-commit/repo0jplamdq/node_env-system/lib/node_modules/markdown-link-check/markdown-link-check:37
.version(pkg.version)
^
TypeError: program.version is not a function
at getInputs (/home/runner/.cache/pre-commit/repo0jplamdq/node_env-system/lib/node_modules/markdown-link-check/markdown-link-check:37:10)
at main (/home/runner/.cache/pre-commit/repo0jplamdq/node_env-system/lib/node_modules/markdown-link-check/markdown-link-check:265:20)
Node.js v18.20.2
Asciidoc Link Check......................................................Passed
- hook id: asciidoc-link-check
- duration: 15.99s
```
