### ISSUE TITLE
3.13.6 not outputting errors

### ISSUE THREAD

**Issue by WillGibson** [tcort/markdown-link-check#412]
Running in the pre-commit hook with this config...

```
repos:
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2
    hooks:
      - id: markdown-link-check
        args:
          - --quiet
          - --config
          - .markdown-link-check.json
```

...we get this output, which is good...

```
➜ pre-commit run --all-files                                      
Markdown Link Check......................................................Failed
- hook id: markdown-link-check
- exit code: 1


  ERROR: 1 dead links found in docs/get-started/deploy-a-service.md !
  [✖] ../MAKE-IT-DEAD-LINK-reference/terminology.md#internet-facing-service → Status: 400
```

Bump the version to v3.13.6 and the detail of the error seems to be gone...

```
➜ pre-commit run --all-files
Markdown Link Check......................................................Failed
- hook id: markdown-link-check
- exit code: 1
```

Even without quiet mode it is not outputting the errors.

Is that a bug or something we configured wrong?
